FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm

# ---------------------------------------------------
# uv
# ref: https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
# ---------------------------------------------------
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# ---------------------------------------------------
# 依存パッケージやビルド・デバッグ用ツールなど
# ---------------------------------------------------
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    locales-all \
    && apt autoremove -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------
# ロケール
# ---------------------------------------------------
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

# ---------------------------------------------------
# 環境変数
# ---------------------------------------------------
ENV LOG_FILE_NAME=app_prod.log

# ---------------------------------------------------
# アプリケーションコードのコピー
# ---------------------------------------------------
WORKDIR /app/logs
WORKDIR /app
COPY ./src /app

# ---------------------------------------------------
# Pythonパッケージのインストール
# ---------------------------------------------------
COPY requirements.txt .python-version pyproject.toml uv.lock /app/
RUN uv sync --frozen

# CMD [ "python", "run.py" ]
CMD [ "uv", "run", "run.py" ]
